#!/usr/bin/env bash
MAINPATH=$(dirname "$0")

mkdir -p ~/.config/nvim

cp -v $MAINPATH/config/.zshrc		~
cp -v $MAINPATH/config/.irbrc		~
cp -v $MAINPATH/config/.tmux.conf	~
cp -v $MAINPATH/config/init.vim		~/.vimrc
cp -v $MAINPATH/config/init.vim		~/.config/nvim/
cp -v $MAINPATH/config/config.fish	~/.config/fish/

cp -v $MAINPATH/config/.ideavimrc	~

