#!/usr/bin/env bash
MAINPATH=$(dirname "$0")

mkdir -p ~/.config/nvim

ln -s $MAINPATH/config/.zshrc		~
ln -s $MAINPATH/config/.irbrc		~
ln -s $MAINPATH/config/.tmux.conf	~
ln -s $MAINPATH/config/init.vim		~/.vimrc
ln -s $MAINPATH/config/init.vim		~/.config/nvim/
ln -s $MAINPATH/config/config.fish	~/.config/fish/

ln -s $MAINPATH/config/.ideavimrc	~

